version: '3.8'
services:
  synthesizer:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - ./backend:/app/backend
    # command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload


networks:
  default:
    name: roadrunner-network
    external: true