"""Create items table

Revision ID: b332d401312c
Revises: 
Create Date: 2024-09-29 13:18:14.558671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b332d401312c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_id'), 'items', ['id'], unique=False)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=False)
    op.drop_index('idx_dolocation_id', table_name='nyc_yellow_taxi_trips')
    op.drop_index('idx_dropoff_datetime', table_name='nyc_yellow_taxi_trips')
    op.drop_index('idx_pickup_datetime', table_name='nyc_yellow_taxi_trips')
    op.drop_index('idx_pulocation_id', table_name='nyc_yellow_taxi_trips')
    op.drop_table('nyc_yellow_taxi_trips')
    op.drop_index('flyway_schema_history_s_idx', table_name='flyway_schema_history')
    op.drop_table('flyway_schema_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flyway_schema_history',
    sa.Column('installed_rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('script', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('installed_by', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('installed_rank', name='flyway_schema_history_pk')
    )
    op.create_index('flyway_schema_history_s_idx', 'flyway_schema_history', ['success'], unique=False)
    op.create_table('nyc_yellow_taxi_trips',
    sa.Column('vendorid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tpep_pickup_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('tpep_dropoff_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('passenger_count', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('trip_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ratecodeid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('store_and_fwd_flag', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.Column('pulocationid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dolocationid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fare_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('extra', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('mta_tax', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tip_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tolls_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('improvement_surcharge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('congestion_surcharge', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('airport_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index('idx_pulocation_id', 'nyc_yellow_taxi_trips', ['pulocationid'], unique=False)
    op.create_index('idx_pickup_datetime', 'nyc_yellow_taxi_trips', ['tpep_pickup_datetime'], unique=False)
    op.create_index('idx_dropoff_datetime', 'nyc_yellow_taxi_trips', ['tpep_dropoff_datetime'], unique=False)
    op.create_index('idx_dolocation_id', 'nyc_yellow_taxi_trips', ['dolocationid'], unique=False)
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
