"""Allow duplication on customer email

Revision ID: ead768ba9394
Revises: ec3c43ba7fd5
Create Date: 2024-10-03 13:53:54.399640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead768ba9394'
down_revision: Union[str, None] = 'ec3c43ba7fd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_email', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=True)
    # ### end Alembic commands ###
