"""Ensure autoincrement on inqury id

Revision ID: ec3c43ba7fd5
Revises: f66502d5944c
Create Date: 2024-10-03 13:52:02.050427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3c43ba7fd5'
down_revision: Union[str, None] = 'f66502d5944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
