"""Add autoincrement to id fields

Revision ID: f1fac3414717
Revises: c95bfb7cf05a
Create Date: 2024-10-03 13:22:55.756989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fac3414717'
down_revision: Union[str, None] = 'c95bfb7cf05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
